source "https://rubygems.org"

ruby "3.3.0"

marj_version = File.read('../app/models/marj.rb').match(/VERSION = '([^']*)'/)[1]

gem "marj", marj_version, path: "../"
gem "rails", "~> 7.1.3"
gem "sqlite3", "~> 1.4"
