# frozen_string_literal: true

source 'https://rubygems.org'

gem 'marj', path: '../'
gem 'mission_control-jobs'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.1.3'
gem 'rspec-core', '~> 3.0'
gem 'rspec-expectations', '~> 3.0'
gem 'rspec-mocks', '~> 3.0'
gem 'rspec-rails', '~> 6.1'
gem 'sprockets-rails'
gem 'sqlite3', '~> 1.4'
