# frozen_string_literal: true

source 'https://rubygems.org'

marj_version = File.read('../lib/marj_record.rb').match(/VERSION = '([^']*)'/)[1]

gem 'marj', marj_version, path: '../'
gem 'sqlite3', '~> 1.4'
