name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version'
      next_version:
        type: string
        description: 'Next Version'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: Release
        env:
          VERSION: ${{ inputs.version }}
          NEXT_VERSION: ${{ inputs.next_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: make release
