name: Build, Lint & Test

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!**/*.md'
      - '!/.release-notes'
      - '!/script/release.rb'
      - '!/script/console.rb'
      - '!/LICENSE.txt'
      - '!/.github/dependabot.yml'
      - '!/.github/workflows/release.yml'

jobs:
  build-lint-test-2-7-0-sqlite:
    name: Build, Lint, Test (2.7.0, SQLite)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.0'
      - name: Lint
        run: make rubocop
      - name: Unit
        run: make unit-sqlite
      - name: Integration
        run: make integration
  build-lint-test-coverage-doc-3-3-0-sqlite:
    name: Build, Lint, Test, Coverage, Doc (3.3.0, SQLite)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
      - name: Lint
        run: make rubocop
      - name: Unit
        run: make unit-sqlite
      - name: Integration
        run: make integration
      - name: Coverage
        run: make coverage
  unit-3-3-0-mysql:
    name: Unit (3.3.0, MySQL)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
      - name: Test
        run: make unit-mysql
  unit-3-3-0-postgres:
    name: Unit (3.3.0, PostgreSQL)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
      - name: Test
        run: make unit-postgres
